services:
  - type: web
    name: lomustrack
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000
      - key: SECRET_KEY
        generateValue: true
      - key: META_GRAPH_API_VERSION
        value: v25.0
      - key: DATABASE_URL
        fromDatabase:
          name: lomustrack-db
          property: connectionString

databases:
  - name: lomustrack-db
    databaseName: logpose
    user: postgres
    plan: free
    region: oregon
